### ISSUE TITLE
StaticCompiler for v1.11

### ISSUE THREAD

**Issue by Thomas008** [tshort/StaticCompiler.jl#166]
So far julia v1.11 rc1 and rc2 are out. Do you plan to have run StaticCompiler for julia v.11? This would be very great! StaticCompiler is an amazing tool.  Or do you wait until the stable final version v.11 is being published?
When trying to compile (install) StaticCompiler on rc1 and rc2 errors come up. E.g. in rc2 the error message is

`ERROR: LoadError: InitError: type Nothing has no field major
Stacktrace:
  [1] getproperty
    @ .\Base.jl:49 [inlined]
  [2] __init__()
    @ GPUCompiler C:\Users\Sunito\.julia\packages\GPUCompiler\kqxyC\src\GPUCompiler.jl:64
  [3] run_module_init(mod::Module, i::Int32)
    @ Base .\loading.jl:1263
  [4] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base .\loading.jl:1251
  [5] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any}, ignore_native::Nothing)
    @ Base .\loading.jl:1195
  [6] _include_from_serialized
    @ .\loading.jl:1152 [inlined]
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128, stalecheck::Bool; reasons::Dict{String, Int32}, DEPOT_PATH::Vector{String})
    @ Base .\loading.jl:1917
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:2378
  [9] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2243
 [10] #invoke_in_world#3
    @ .\essentials.jl:1077 [inlined]
 [11] invoke_in_world
    @ .\essentials.jl:1074 [inlined]
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2230
 [13] macro expansion
    @ .\loading.jl:2169 [inlined]
 [14] macro expansion
    @ .\lock.jl:273 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2126
 [16] #invoke_in_world#3
    @ .\essentials.jl:1077 [inlined]
 [17] invoke_in_world
    @ .\essentials.jl:1074 [inlined]
 [18] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2119
 [19] include
    @ .\Base.jl:558 [inlined]
 [20] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base .\loading.jl:2749
 [21] top-level scope`

**Comment by Robert-j7** [comment]
This is probably related to [#631](https://github.com/JuliaGPU/GPUCompiler.jl/issues/610) and bumping the `GPUCompiler` version dependency to `0.27.0` should resolve this.

**Comment by Thomas008** [comment]
Installing GPUCompiler 0.27.x under 1.11 is fine.
However, when installing StaticCompiler I still get the error mentioned above.

**Comment by Thomas008** [comment]
The reasons seems to be that StaticCompiler takes an old version of GPUCompiler.
GPUCompiler v0.27.x (or higher) work in julia 1.11 (or newer versions).
The current `Project.toml` file of StaticCopmiler seems to be not made for julia 1.11 (or higher).
It uses GPUCompiler v0.26 and lower.

**Comment by schlichtanders** [comment]
https://github.com/tshort/StaticCompiler.jl/issues/170 tried to upgrade the GPUCompiler version and failed so far...
is there any progress on making StaticCompiler work on julia 1.11?

**Comment by brenhinkeller** [comment]
I'm sure it's possible, but it seems like there have been a lot of changes to GPUCompiler in the interim. If anyone wants to try figuring out what all needs to be changed to work with v1.x of GPUCompiler, it might be possible to get one of the GPUCompiler folks to advise on how best to go about it..

**Comment by brenhinkeller** [comment]
Completed in #181
